### ISSUE TITLE
Expose API

### ISSUE THREAD

**Issue by 8eecf0d2** [8eecf0d2/netlify-local#6]
Would be handy to expose an API so test runners can start & stop the server, optionally with the build system.

### Usage

```ts
import { parseNetlifyConfig, parseWebpackConfig, Server, Webpack } from "netlify-local";

const netlifyConfig = parseNetlifyConfig("netlify.toml");
const port = 3000;
const server = new Server({
  netlifyConfig: netlifyConfig,
  routes: {
    static: true,
    lambda: true,
  },
  port: 9000,
});
await server.listen();
await server.close();

const webpackConfig = parseWebpackConfig("webpack.config.js");
const webpack = new Webpack(webpackConfig);
await webpack.build();
webpack.watch();
```

#### Config
- [x] `parseNetlifyConfig()`
- [x] `parseWebpackConfig()`

#### Server
- [x] `constructor`
- [x] `Server.listen()`
- [x] `Server.close()`

#### Webpack
- [x] `constructor`
- [x] `Webpack.build()`
- [x] `Webpack.watch()`

**Comment by 8eecf0d2** [comment]
Keeping this open until thoroughly tested.

**Comment by 8eecf0d2** [comment]
Hmm, currently writing some `Server` tests so I'll see if I can reproduce, all I can suggest for now is to try with [**0.4.0**](https://github.com/8eecf0d2/netlify-local/releases/tag/0.4.0).

**Comment by 8eecf0d2** [comment]
Unable to reproduce unfortunately, I'm guessing you've got some more exotic toml usage which `netlify-local` is not able to handle gracefully - although a `TypeError` seems odd..

If you're able to provide your `netlify.toml` or something with similar structure I'd be happy to test further.

**Comment by Levino** [comment]
The error was because I do not have a `publish` entry in my netlify.toml. I do things differently now: I write express handlers instead of lambda function handlers. I then use `serverless-http` to bundle one app per express handler as a lambda function handler. I then test my express apps and hope that the bundling via `serverless-http` does not make any issues.

**Comment by 8eecf0d2** [comment]
Updated OP with correct API usage as of [**1.0.0**](https://github.com/8eecf0d2/netlify-local/releases/tag/1.0.0).

**Comment by 8eecf0d2** [comment]
_Closing this as it appears to be working as expected in tests and real world usage._
